// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/wizgg/qmk_firmware/keyboards/jadookb/big_knob/gfx/winxp/winxp.gif --output /home/wizgg/qmk_firmware/keyboards/jadookb/big_knob/gfx/winxp --format rgb565 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_winxp_length;
extern const uint8_t  gfx_winxp[26532];
